"""add new coloe

Revision ID: 61749817291c
Revises: 03d89be2fd6c
Create Date: 2018-10-07 22:58:44.563292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61749817291c'
down_revision = '03d89be2fd6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_id', table_name='users')
    op.drop_table('users')
    op.drop_index('logisticCode', table_name='record_list')
    op.drop_table('record_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record_list',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('logisticCode', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('ShipperCode', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('ShipperCode2', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('receiver', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('shipDate', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('creater', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('shippingMoney', mysql.FLOAT(), nullable=True),
    sa.Column('logisticsInfo', mysql.VARCHAR(length=10240), nullable=True),
    sa.Column('latestLogisticsInfo', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('logisticsState', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('update_time', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('deleted', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_index('logisticCode', 'record_list', ['logisticCode'], unique=True)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('fullname', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('role', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('group_name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('create_time', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('update_time', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_index('user_id', 'users', ['user_id'], unique=True)
    # ### end Alembic commands ###
